### ISSUE TITLE
0.1.5 fix breaks module installation (Restrict ipaddress dependency to Python < 3.3)

### ISSUE THREAD

**Issue by guirem** [pydron/ifaddr#14]
Change in setup.py file due to PR merge https://github.com/pydron/ifaddr/pull/12
`install_requires = ['ipaddress;python_version<"3.3"'],` 
breaks module installation (on some OS).

Pip version : pip 1.5.6 from /usr/lib/python3/dist-packages (python 3.4)

It did not happen for 0.1.4 so this is clearly due to this change not recognized by setuptools

Output from pip command
```
Downloading/unpacking zeroconf
  Downloading zeroconf-0.21.3-py2.py3-none-any.whl
Downloading/unpacking ifaddr (from zeroconf)
  Downloading ifaddr-0.1.5.tar.gz
  Running setup.py (path:/tmp/pip-build-timp37am/ifaddr/setup.py) egg_info for package ifaddr
    error in ifaddr setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
    Complete output from command python setup.py egg_info:
    error in ifaddr setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
```

**Comment by pydron** [comment]
Might be due to an older version of setuptools. Setup markers (PEP 508) require setuptools v20.8.1 or newer: https://stackoverflow.com/questions/21082091/install-requires-based-on-python-version

Can you check if updating setuptools solves the issue?

Looks like PEP-518 is addressing the issue of defining minimum versions of build tools, but that will require a rather recent version of pip to work. 

I woudn't mind if someone could provide a patch to define the setuptools dependencies according to PEP-518. Preferably in a way that still works with older pip versions. I'm not actively working on ifaddr at the moment, but I do try to pull in fixes.

**Comment by guirem** [comment]
Hi,
Running the command `sudo pip3 install setuptools --upgrade` did not work.
To get it working installation of python3-setuptools was necessary (only python3-pip was installaed via apt.

Note that it happened when trying to install zerconf package (ifaddr is in the 'install_requires'). 
This package also has conditional dependance definition in setup.py but the error only seems to come when trying to install ifaddr (https://github.com/jstasiak/python-zeroconf/blob/master/setup.py).
So my understanding is that Setup markers (PEP 508) are not completely rejected.

Is that possible that is has to do with binary distribution tooling version (using wheels). 
I read somewhere that it could be the reason but can't recall the link...

**Comment by henfri** [comment]
Hello,

I am experiencing the same problem. I am starting with a fresh install of python (debian jessie) and installing the latest version (available in debian) of setuptools with apt.
This gives me setuptools 5.5.1...

It would be nice if ifaddr could be backwardcompatible.

Regards,
Hendrik

**Comment by kdschlosser** [comment]
i submitted a PR for this issue #16. it has to do with the version of setup tools that you are running. I would have to check specifically what version supports the syntax used for the install requires line. but if you run this command it will upgrade setup tools to the latest version and you can give that a go and see if it will install then. and if not the person that did the PR for the install_requires is not running the latest version. 

    python -m pip install --upgrade setuptools


either way it doesn't really matter. it's broken at this point. The PR i submitted has a solution where it is not dependent on the setup tools version.

**Comment by henfri** [comment]
Thanks!

**Comment by pydron** [comment]
I've released 0.1.6 with @kdschlosser's fix. 

Please let me know if that helped. 

It might not be perfect, the version is only checked when setup.py is run. but since this package is shipped as a source distribution, we might be fine.

I've changed `requires` back to `install_requires` as I couldn't find any good documentation for `requires`. It seems that `install_requires` is recommended, and it used to work for this project before.

**Comment by kdschlosser** [comment]
however you want to go about doing it. it all depends on how the program is being distributed (wheel, source....). the information below is some good reading. the links also give some really good information as well..

I also believe you would need to look at the documentation for distutils about the requires parameter because setuptools is an extension of distutils. install_requires is specific to setuptools. and requires is in setuptools and distutils.

https://doughellmann.com/blog/2007/11/25/requiring-packages-with-distutils/

so if you wanted to have code not dependent on a setuptools installation. some linux distros do not have setuptools pre installed. one could write the code like the example below when handling the import of setuptools. but you would need to change the install_requires back to requires because distutils does not support install_requires.

    try:
        from setuptools import setup
    except ImportError:
        from distutils.core import setup

this would give the best possible coverage of installation possibilities without the need to rely on a non std lib package installer being installed. I do not have a lot of knowledge on the inner workings of PIP and what it likes to see. and I do know that pip is the favored package installer.

the way the python version is parsed in the PR will not carry over if building a wheel. that is where the previous PR would be the route to go. I think that syntax only works in setuptools version that are >= 36.1 (or something near there). the support for that syntax the previous author did got put into setuptools about a year ago. which means that it is not a widely used mechanism. just yet. unless there is a need to use bdist_wheel as a command line argument to build the package into a wheel I would opt for the requires.

this is probably the best information on the various mechanisms that can be used to install requirements. and it is all based on how you want to package the program.

https://hynek.me/articles/conditional-python-dependencies/

**Comment by jstasiak** [comment]
Next releases will have both source and wheel distributions. I brought the environment marker back in order to be able to build universal wheels, but
a) today way more people should have modern setuptools (with environment marker support) available
b) even if they don't, installing wheels with optional dependencies only requires pip >= 1.4

**Comment by kdschlosser** [comment]
I wrote a packaging add-on for distutils that builds wheels and eggs without having any additional requirements. It also handles universal wheels and if compiling c extensions or modules if the os is Windows it will create the universal wheel that is appropriate for the compiler version that python has been compiled with. This is important because of changes in the runtime of the compiler in the different versions. So if C extensions are compiled then the universal grouping would be as follows.

python versions 3.5, 3.6, 3.7 and 3.8 are compiled with MSVC 14.x
python versions 3.3 and 3.4 are MSVC 10.0
and python versions 2.6, 2.7, 3.0, 3.1 and 3.2 used MSVC 9.0

So on Windows those are how the universal wheels would have to be grouped, and a build for each of the groupings would need to be done for x86 and x64. so a total of 6 builds for Windows. 

I do not believe that POSIX systems have this issue or none that I was able to locate. There would need to be different builds because of changes to the python c API and the architecture. 

If not compiling any extensions then a single universal wheel can be created easily.

I do not remember if I have posted the code for that add-on to github as of yet. But if you are interested in it let me know. It is actually not that large and is easily added to any existing build system.

I have also written a distutils add-on for sphinx if this is something you use. Removed the need to have a config.py file for sphinx and places all control right into the command line when running the setup program. if that is also of interest let me know.
